name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v3.0.0 
        with: 
              node-version: "16.X"

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build
        
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
            source: 'dist/*'
            host: ${{ secrets.REMOTE_HOST }}
            target: ${{ secrets.REMOTE_PATH }}
            port: ${{ secrets.SERVER_PORT }}
            username: ${{ secrets.USER_NAME }}
            key: ${{ secrets.SSH_KEY }}

      
